### ISSUE TITLE
2.0.8运行出错

### ISSUE THREAD

**Issue by zzy080615** [LiWenHui96/flutter_file_view#10]
flutter_file_view-2.0.8+3/android/src/main/kotlin/com/file/view/LocalFileViewer.kt: (109, 45): Type mismatch: inferred type is Boolean? but Boolean was expected

**Comment by antonioCaballero17** [comment]
Hi @zzy080615 I had exactly the same issue yesterday. I solve that using Elvis operator in line 109 of LocalFileViewer.kt.
replace
`            "openFile" -> openTbsReaderView(call.arguments())
`
`            "openFile" -> openTbsReaderView(call.arguments()?:true)
`

That is a provisional solutions, until @LiWenHui96 repair it

**Comment by ChenJinCan** [comment]
me too

**Comment by LiWenHui96** [comment]
已发布 2.0.8+4 版本解决.
