### ISSUE TITLE
word文档下载后乱码

### ISSUE THREAD

**Issue by andya1985** [LiWenHui96/flutter_file_view#11]
NetworkFileViewer(
                      downloadUrl: downloadUrl,
                      downloadPath: downloadPath,
                      onViewPressed: () {
                        push(LocalFileViewerPage(downloadPath));
                      },
                    ));
下载word文件后，文件内容乱码，需要加什么参数吗？

**Comment by LiWenHui96** [comment]
文档需要进行相对应的编码方式，后续版本中会有所体现。

**Comment by LiWenHui96** [comment]
目前已发布 2.1.0-alpha.1 版本，如果还出现问题，请重新打开。
