### ISSUE TITLE
获取文件大小失败

### ISSUE THREAD

**Issue by liulin824** [LiWenHui96/flutter_file_view#12]
不知道我的描述是否准确，通过nginx映射到的文件是可以正常获取到文件大小的，当我的文件链接是alioss或者经后端的时候是获取失败的。 具体文件如下
![image](https://user-images.githubusercontent.com/80634299/191889100-544c848e-5b78-47b7-a1a9-02ff327116e8.png)

**Comment by LiWenHui96** [comment]
文件大小的获取方式是根据header获取的，并不保证全部获取成功，并在后续的版本中剔除此功能

**Comment by LiWenHui96** [comment]
目前已发布 2.1.0-alpha.1 版本，不再使用 `NetWorkFileViewer`，请使用新版本吧。

**Comment by liulin824** [comment]
好的，谢谢
