### ISSUE TITLE
SDK 44216及以上版本支持Android 13

### ISSUE THREAD

**Issue by supermebing** [LiWenHui96/flutter_file_view#14]
版本：44226

更新日期：2022-9-5

说明：1、修复一些问题 2、SDK 44216及以上版本支持Android 13

**Comment by LiWenHui96** [comment]
目前 `44199` 版本后，不再对 `TbsReaderView` 进行维护。 TBS的版本后续不会再进行更新。

**Comment by supermebing** [comment]
明白👌🏻
