### ISSUE TITLE
file exists, but plugin says it is non-existant.

### ISSUE THREAD

**Issue by DeanPack** [LiWenHui96/flutter_file_view#15]
I am using this plugin to display files that I have downloaded using http get and saved to local storage. When I give the plugin the directory to look in it says that the file doesn't exist. The path I'm saving the file to looks like this
```
/Users/myuser/Library/Developer/CoreSimulator/Devices/BD738457-C105-43FE-A38A-60B401052DDC/data/Containers/Data/Application/AA3FCA19-D06E-4129-917F-39032F261F0C/Documents/67c1dcdf-aea7-406e-a7c6-79f685061751.pdf
```
the file does exist there and I can open it, but the simulator can't.

**Comment by LiWenHui96** [comment]
好的，这个问题已经修复，请使用 `2.1.2` 解决它。
