### ISSUE TITLE
小米手机报错 显示插件加载失败

### ISSUE THREAD

**Issue by lumianchan** [LiWenHui96/flutter_file_view#16]
![微信图片_20221105165457](https://user-images.githubusercontent.com/22650245/200111965-52707c92-ba11-46bd-9a91-2c9a88b6db08.jpg)
W/System.err( 9156): java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.tencent.tbscommon.plugin.exports.QBPluginItemInfo.mPackageSize' on a null object reference
W/System.err( 9156): 	at com.tencent.tbs.tbsshell.partner.reader.service.l$a.getPackageSize(TbsJavaCore:1)
W/System.err( 9156): 	at com.tencent.mtt.external.reader.internal.v.b(Unknown Source:14)
W/System.err( 9156): 	at com.tencent.mtt.external.reader.internal.t.a(Unknown Source:10)
W/System.err( 9156): 	at com.tencent.mtt.external.reader.internal.l.a(Unknown Source:26)
W/System.err( 9156): 	at com.tencent.mtt.external.reader.internal.l$b.a(Unknown Source:194)
W/System.err( 9156): 	at com.tencent.mtt.external.reader.a.p$c.handleMessage(Unknown Source:11)
W/System.err( 9156): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err( 9156): 	at android.os.Looper.loop(Looper.java:236)
W/System.err( 9156): 	at android.app.ActivityThread.main(ActivityThread.java:8060)
W/System.err( 9156): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 9156): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
W/System.err( 9156): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by LiWenHui96** [comment]
tbs内部问题，与插件无关。
