### ISSUE TITLE
Failed to initialize engine error in android

### ISSUE THREAD

**Issue by Anish-T-GitHub** [LiWenHui96/flutter_file_view#26]
I try to open local asset files in android but always returning Failed to initialize engine.

**Comment by Anish-T-GitHub** [comment]
Please fix this issue.

**Comment by Anish-T-GitHub** [comment]
Logs 
====
D/com.file.view.FlutterFileViewPlugin(28631): FlutterFileView: TBS - Ready to initialize.
D/com.file.view.FlutterFileViewPlugin(28631): FlutterFileView: TBS - Start the initialization.
W/leview.filevie(28631): Accessing hidden method Ldalvik/system/VMRuntime;->getRuntime()Ldalvik/system/VMRuntime; (greylist,core-platform-api, reflection, allowed)
W/leview.filevie(28631): Accessing hidden method Ldalvik/system/VMRuntime;->is64Bit()Z (greylist,core-platform-api, reflection, allowed)
I/TetheringManager(28631): registerTetheringEventCallback:com.fileview.fileview
I/System.out(28631): [okhttp]:check permission begin!
I/System.out(28631): [okhttp]:not MMS!
I/System.out(28631): [okhttp]:not Email!
I/System.out(28631): [socket]:check permission begin!
I/System.out(28631): [okhttp]:check permission begin!
I/System.out(28631): [okhttp]:not MMS!
I/System.out(28631): [okhttp]:not Email!
I/System.out(28631): [socket]:check permission begin!
W/System.err(28631): java.net.SocketException: Connection reset
W/System.err(28631): 	at java.net.SocketInputStream.read(SocketInputStream.java:215)
W/System.err(28631): 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
W/System.err(28631): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
W/System.err(28631): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
W/System.err(28631): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
W/System.err(28631): 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
W/System.err(28631): 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
W/System.err(28631): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
W/System.err(28631): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
W/System.err(28631): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
W/System.err(28631): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
W/System.err(28631): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
W/System.err(28631): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
W/System.err(28631): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:302)
W/System.err(28631): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
W/System.err(28631): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
W/System.err(28631): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
W/System.err(28631): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
W/System.err(28631): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
W/System.err(28631): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
W/System.err(28631): 	at com.tencent.smtt.utils.g.a(Unknown Source:1)
W/System.err(28631): 	at com.tencent.smtt.utils.g.a(Unknown Source:121)
W/System.err(28631): 	at com.tencent.smtt.sdk.TbsDownloader.b(Unknown Source:403)
W/System.err(28631): 	at com.tencent.smtt.sdk.TbsDownloader.a(Unknown Source:0)
W/System.err(28631): 	at com.tencent.smtt.sdk.TbsDownloader$1.handleMessage(Unknown Source:257)
W/System.err(28631): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(28631): 	at android.os.Looper.loop(Looper.java:236)
W/System.err(28631): 	at android.os.HandlerThread.run(HandlerThread.java:67)
W/System.err(28631): org.json.JSONException: Value ["HttpError"] of type org.json.JSONArray cannot be converted to JSONObject
W/System.err(28631): 	at org.json.JSON.typeMismatch(JSON.java:112)
W/System.err(28631): 	at org.json.JSONObject.<init>(JSONObject.java:169)
W/System.err(28631): 	at org.json.JSONObject.<init>(JSONObject.java:182)
W/System.err(28631): 	at com.tencent.smtt.sdk.TbsDownloader.a(Unknown Source:78)
W/System.err(28631): 	at com.tencent.smtt.sdk.TbsDownloader.b(Unknown Source:476)
W/System.err(28631): 	at com.tencent.smtt.sdk.TbsDownloader.a(Unknown Source:0)
W/System.err(28631): 	at com.tencent.smtt.sdk.TbsDownloader$1.handleMessage(Unknown Source:257)
W/System.err(28631): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(28631): 	at android.os.Looper.loop(Looper.java:236)
W/System.err(28631): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/com.file.view.FlutterFileViewPlugin(28631): FlutterFileView: TBS - Download completed - -106 - FAIL
D/com.file.view.FlutterFileViewPlugin(28631): FlutterFileView: TBS - onCoreInitFinished
D/com.file.view.FlutterFileViewPlugin(28631): FlutterFileView: TBS - Core Init - FAIL
I/leview.filevie(28631): ProcessProfilingInfo new_methods=1312 is saved saved_to_disk=1 resolve_classes_delay=8000
D/com.file.view.FlutterFileViewPlugin(28631): FlutterFileView: TBS - Current Status - ERROR

**Comment by LiWenHui96** [comment]
目前腾讯已经停止服务，所以Android不再受支持，后续版本就会放弃Android平台。
另外腾讯提供了文档浏览引擎SDK（付费使用）
https://mp.weixin.qq.com/s/rmSa4Fs77MDdjFioRKwXPA
