### ISSUE TITLE
 Error: The getter 'titleMedium' isn't defined for the class 'TextTheme'.

### ISSUE THREAD

**Issue by Abdullahfoysal** [LiWenHui96/flutter_file_view#3]
Error: The getter 'bodyMedium' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyMedium'.
        style: widget.fileSizeStyle ?? Theme.of(context).textTheme.bodyMedium,

**Comment by LiWenHui96** [comment]
> Error: The getter 'bodyMedium' isn't defined for the class 'TextTheme'.
> 
> * 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyMedium'.
>   style: widget.fileSizeStyle ?? Theme.of(context).textTheme.bodyMedium,

Please use version 2.0.3 to get rid of this problem.
