### ISSUE TITLE
Error!!! Files does not open

### ISSUE THREAD

**Issue by Princewil** [LiWenHui96/flutter_file_view#4]
![IMG-20220325-WA0008](https://user-images.githubusercontent.com/40724883/160117770-3f50b2e1-5f67-4459-b3ff-669b84cb8b0c.jpg)

I have tried everything, yet I keep getting this issue, for all file type. Pls is there something I'm missing?

**Comment by LiWenHui96** [comment]
> ![IMG-20220325-WA0008](https://user-images.githubusercontent.com/40724883/160117770-3f50b2e1-5f67-4459-b3ff-669b84cb8b0c.jpg)
> 
> I have tried everything, yet I keep getting this issue, for all file type. Pls is there something I'm missing?

I think it may be caused by the problem of [Tencent X5](https://x5.tencent.com/docs/index.html). You can pay attention to his problem.

**Comment by Princewil** [comment]
Pls what do I do?
How do I pay attention to "his" problem?
Are you facing similar issues or it's just me?

**Comment by LiWenHui96** [comment]
> Pls what do I do?
> How do I pay attention to "his" problem?
> Are you facing similar issues or it's just me?

这里指的插件加载失败是腾讯X5内部的报错信息，可能是网络问题导致的下载失败或者其他原因。可咨询 [Tencent X5](https://x5.tencent.com/docs/index.html) 官方
