### ISSUE TITLE
新版本tbs怎么适配

### ISSUE THREAD

**Issue by zzy080615** [LiWenHui96/flutter_file_view#9]
因为44085版本的tbs有访问imsi导致华为审核不过，但是我把tbs升级到最新的44226应用安装就闪退，怎么在gradle中配置呢，请教下

**Comment by LiWenHui96** [comment]
目前 44085 后续版本已标记弃用 `TbsReaderView`;

QbSdk内部方法中有关于是否获取 imsi、AndroidID 的方法，会在后续版本内推出。

```
QbSdk.canGetAndroidId(false) // 不获取 AndroidID
QbSdk.canGetDeviceId(false) // 不获取 imsi 等
QbSdk.canGetSubscriberId(false) // 不获取 SubscriberId
```

其他有关 Tencent X5 的问题请查看 [常见问题](https://x5.tencent.com/docs/questions.html)

**Comment by LiWenHui96** [comment]
后续如果仍存在问题请再次打开此issue
